# Generated by Django 5.1 on 2024-10-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutdetail',
            name='reps',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutdetail',
            name='sets',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutdetail',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
